---
- name: create volume
  file:
    path=/opt/consul
    state=directory
    mode=0755

- name: remove consul contenier
  docker:
    name: consul_cluster_node
    image: progrium/consul
    state: absent

- name: setup consul cluster
  docker:
    name: consul_cluster_node
    image: progrium/consul
    command: -server -advertise {{ ansible_host }} -node={{ ansible_hostname }} -bootstrap-expect {{ nodes_in_the_cluster }}
    state: started
    expose:
    - 8300
    - 8301
    - 8302
    ports:
    - "{{ ansible_host }}:8300:8300"
    - "{{ ansible_host }}:8301:8301"
    - "{{ ansible_host }}:8301:8301/udp"
    - "{{ ansible_host }}:8302:8302"
    - "{{ ansible_host }}:8302:8302/udp"
    - "{{ ansible_host }}:8400:8400"
    - "{{ ansible_host }}:8500:8500"
    - "172.17.0.1:53:53/udp"
    volumes:
      - /opt/consul:/data
